language: node_js

services:
  - mysql

node_js:
  - 10.9

cache:
  directories:
    - node_modules

before_install:
  - mysql -e 'CREATE DATABASE testing;'

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run typecheck
  - npm run lint
  - npm run test:client:ci
  - npm run test:server:ci

after_script:
  - npm run test:coverage:combine
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

env:
  globals:
    - APP_SECRET=testing
    - TYPEORM_USERNAME=travis
    - TYPEORM_DATABASE=testing
    - NODE_ENV=testing
